print('Im hungry')
print('I wanna die')
print('What an asshole')
print('You are such an asshole')
print("You are loser")
print('Are you retarded or something?')
print('Fucking bitch')
print('Fucking Mary')
print('Are you fucking out of your mind?')
print('Im gonna fucking beat the shit out of him')
print('Shut the fuck up huh?')
print('Shut your fucking mouth ok?')